baseURL = "https://blog.zoncoen.net/"
enableGitInfo = true
enableRobotsTXT = true
footnoteReturnLinkContents =  "â†©"
googleAnalytics = "UA-42769904-1"
hasCJKLanguage = true
languageCode = "ja-JP"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "solarized-dark"
pygmentsUseClasses = true
rssLimit = 15
theme = "hugo_theme_pickles"
title = "Degorgement"
[permalinks]
    posts = "/:year/:month/:day/:contentbasename/"
[params]
    author = "Kenta Mori"
    authorwebsite = "https://twitter.com/zoncoen"
    avatar = "/images/avatar.png"
    bio = "Software engineer at newmo, Inc."
    contact = "https://twitter.com/zoncoen"
    paginate = 10
    # disqus = "404el"
    facebook = "zoncoen"
    ga_api_key = "UA-42769904-1"
    github = "zoncoen"
    instagram = "zoncoen"
    twitter = "zoncoen"
[blackfriday]
    hrefTargetBlank = true
[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80
  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false
  # Will lower case keywords in both queries and in the indexes.
  toLower = false
  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
